[package]
name = "XSLint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
chumsky = "1.0.0-alpha.7"

[dependencies]
chumsky = "1.0.0-alpha.7"
log = "0.4.21"